# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('duration', models.IntegerField(default=0)),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('total_feed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('is_lab', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('total_feed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('avg_rating', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('total_feed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.ManyToManyField(through='departments.DepartmentCourse', to='departments.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentcourse',
            unique_together=set([('department', 'course')]),
        ),
    ]
