# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.Institute'),
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=set([('institute', 'name')]),
        ),
    ]
